"""create initial database schema

Revision ID: 32c00ecf8ae2
Revises: 
Create Date: 2026-08-23 19:58:34.515452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32c00ecf8ae2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'dormant')", name='ck_organisation_status'),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('review_standard_clause',
    sa.Column('standard_clause_id', sa.UUID(), nullable=False),
    sa.Column('clause_number', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('standard_clause_id'),
    sa.UniqueConstraint('clause_number', name='uq_review_standard_clause_clause_number')
    )
    op.create_table('team_member',
    sa.Column('member_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('practice', sa.Text(), nullable=True),
    sa.Column('can_approve', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('partner', 'senior_associate', 'associate', 'paralegal')", name='ck_team_member_role'),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('contract',
    sa.Column('contract_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('privileged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('content_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'ar')", name='ck_contract_language'),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.org_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index('ix_contract_org_id', 'contract', ['org_id'], unique=False)
    op.create_table('data_room_file',
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('privileged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('content_uri', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.org_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('ix_data_room_file_org_id', 'data_room_file', ['org_id'], unique=False)
    op.create_table('matter_assignment',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['team_member.member_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.org_id'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('member_id', 'org_id', name='uq_matter_assignment_member_org')
    )
    op.create_table('obligation',
    sa.Column('obligation_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('band', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.org_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['team_member.member_id'], ),
    sa.PrimaryKeyConstraint('obligation_id')
    )
    op.create_index('ix_obligation_band', 'obligation', ['band'], unique=False)
    op.create_index('ix_obligation_org_due_date', 'obligation', ['org_id', 'due_date'], unique=False)
    op.create_table('request',
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('requester_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=True),
    sa.Column('request_type', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('intake', 'classified', 'access_denied', 'processing', 'escalated', 'drafted', 'awaiting_approval', 'approved', 'edited', 'rejected', 'insufficient')", name='ck_request_status'),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.org_id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['team_member.member_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('access_decision',
    sa.Column('access_decision_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('member_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.CheckConstraint("outcome IN ('authorized', 'unauthorized')", name='ck_access_decision_outcome'),
    sa.ForeignKeyConstraint(['member_id'], ['team_member.member_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.org_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.PrimaryKeyConstraint('access_decision_id')
    )
    op.create_index('ix_access_decision_member_org_decided_at', 'access_decision', ['member_id', 'org_id', 'decided_at'], unique=False)
    op.create_index('ix_access_decision_request_id', 'access_decision', ['request_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('audit_event_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('detail_reference', sa.Text(), nullable=True),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['team_member.member_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.PrimaryKeyConstraint('audit_event_id')
    )
    op.create_index('ix_audit_event_event_type_occurred_at', 'audit_event', ['event_type', 'occurred_at'], unique=False)
    op.create_index('ix_audit_event_request_occurred_at', 'audit_event', ['request_id', 'occurred_at'], unique=False)
    op.create_table('contract_clause',
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.Text(), nullable=False),
    sa.Column('clause_label', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('checklist_area', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.contract_id'], ),
    sa.PrimaryKeyConstraint('clause_id')
    )
    op.create_index('uq_contract_clause_contract_label', 'contract_clause', ['contract_id', 'clause_label'], unique=True, postgresql_where=sa.text('clause_label IS NOT NULL'))
    op.create_table('draft',
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approval_state', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_state IN ('awaiting_approval', 'approved', 'edited', 'rejected')", name='ck_draft_approval_state'),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.PrimaryKeyConstraint('draft_id')
    )
    op.create_index('ix_draft_request_approval_state', 'draft', ['request_id', 'approval_state'], unique=False)
    op.create_table('escalation',
    sa.Column('escalation_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('obligation_id', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('routed_to_id', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('litigation', 'statutory_question', 'sharia_ruling', 'missed_deadline')", name='ck_escalation_reason'),
    sa.CheckConstraint('(request_id IS NOT NULL AND obligation_id IS NULL) OR (request_id IS NULL AND obligation_id IS NOT NULL)', name='ck_escalation_exactly_one_target'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligation.obligation_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.ForeignKeyConstraint(['routed_to_id'], ['team_member.member_id'], ),
    sa.PrimaryKeyConstraint('escalation_id')
    )
    op.create_table('finding',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('checklist_area', sa.Text(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('risk_rating', sa.Text(), nullable=True),
    sa.Column('sharia_sensitive_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tricky_case_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index('ix_finding_request_id', 'finding', ['request_id'], unique=False)
    op.create_table('approval_decision',
    sa.Column('approval_decision_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('draft_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name='ck_approval_decision_decision'),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.draft_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['team_member.member_id'], ),
    sa.PrimaryKeyConstraint('approval_decision_id')
    )
    op.create_index('ix_approval_decision_draft_id', 'approval_decision', ['draft_id'], unique=False)
    op.create_table('citation',
    sa.Column('citation_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('contract_clause_id', sa.UUID(), nullable=True),
    sa.Column('standard_clause_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("source_type IN ('contract_clause', 'standard_clause')", name='ck_citation_source_type'),
    sa.CheckConstraint('(contract_clause_id IS NOT NULL AND standard_clause_id IS NULL) OR (contract_clause_id IS NULL AND standard_clause_id IS NOT NULL)', name='ck_citation_exactly_one_source'),
    sa.ForeignKeyConstraint(['contract_clause_id'], ['contract_clause.clause_id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.finding_id'], ),
    sa.ForeignKeyConstraint(['standard_clause_id'], ['review_standard_clause.standard_clause_id'], ),
    sa.PrimaryKeyConstraint('citation_id')
    )
    op.create_index('ix_citation_finding_id', 'citation', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_citation_finding_id', table_name='citation')
    op.drop_table('citation')
    op.drop_index('ix_approval_decision_draft_id', table_name='approval_decision')
    op.drop_table('approval_decision')
    op.drop_index('ix_finding_request_id', table_name='finding')
    op.drop_table('finding')
    op.drop_table('escalation')
    op.drop_index('ix_draft_request_approval_state', table_name='draft')
    op.drop_table('draft')
    op.drop_index('uq_contract_clause_contract_label', table_name='contract_clause', postgresql_where=sa.text('clause_label IS NOT NULL'))
    op.drop_table('contract_clause')
    op.drop_index('ix_audit_event_request_occurred_at', table_name='audit_event')
    op.drop_index('ix_audit_event_event_type_occurred_at', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index('ix_access_decision_request_id', table_name='access_decision')
    op.drop_index('ix_access_decision_member_org_decided_at', table_name='access_decision')
    op.drop_table('access_decision')
    op.drop_table('request')
    op.drop_index('ix_obligation_org_due_date', table_name='obligation')
    op.drop_index('ix_obligation_band', table_name='obligation')
    op.drop_table('obligation')
    op.drop_table('matter_assignment')
    op.drop_index('ix_data_room_file_org_id', table_name='data_room_file')
    op.drop_table('data_room_file')
    op.drop_index('ix_contract_org_id', table_name='contract')
    op.drop_table('contract')
    op.drop_table('team_member')
    op.drop_table('review_standard_clause')
    op.drop_table('organisation')
    # ### end Alembic commands ###
