"""Add embedding columns

Revision ID: d00efa545c34
Revises: d7e4a1b2c35f
Create Date: 2026-08-25 15:09:31.483796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00efa545c34'
down_revision: Union[str, Sequence[str], None] = 'd7e4a1b2c35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_clause', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('review_standard_clause', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_standard_clause', 'embedding')
    op.drop_column('contract_clause', 'embedding')
    # ### end Alembic commands ###
